"""add_job_description_enhanced_fields

Revision ID: 002_job_enhanced
Revises: 001_profile
Create Date: 2026-02-21 08:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002_job_enhanced'
down_revision: Union[str, None] = '001_profile'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns to job_descriptions table
    op.add_column('job_descriptions', sa.Column('employment_type', sa.String(length=50), nullable=True))
    op.add_column('job_descriptions', sa.Column('experience_level', sa.String(length=50), nullable=True))
    op.add_column('job_descriptions', sa.Column('work_mode', sa.String(length=50), nullable=True))
    op.add_column('job_descriptions', sa.Column('salary_range', sa.String(length=100), nullable=True))
    op.add_column('job_descriptions', sa.Column('tech_stack', sa.Text(), nullable=True))
    op.add_column('job_descriptions', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('job_descriptions', sa.Column('keywords', sa.Text(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove the new columns
    op.drop_column('job_descriptions', 'keywords')
    op.drop_column('job_descriptions', 'word_count')
    op.drop_column('job_descriptions', 'tech_stack')
    op.drop_column('job_descriptions', 'salary_range')
    op.drop_column('job_descriptions', 'work_mode')
    op.drop_column('job_descriptions', 'experience_level')
    op.drop_column('job_descriptions', 'employment_type')
    
    # ### end Alembic commands ###
